spring:
  application:
    name: orderService
  config:
    import: configserver:http://localhost:9000

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: kostas
    password: deko12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
